# Generated by Django 4.2.6 on 2023-11-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=10)),
                ('prompt_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_name', models.CharField(max_length=15)),
                ('element_presence', models.BooleanField(default=False)),
                ('root_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captchapractice.captchaimage')),
            ],
        ),
    ]
