# Generated by Django 4.2.6 on 2023-11-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaimage',
            name='slice_count',
            field=models.IntegerField(choices=[(3, '3x3 Grid'), (4, '4x4 Grid'), (5, '5x5 Grid')], default=3),
        ),
    ]
