# Generated by Django 4.2.6 on 2023-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0002_captchaimage_slice_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchaimage',
            name='image_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='prompt_text',
            field=models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200),
        ),
        migrations.AlterField(
            model_name='imageslice',
            name='slice_name',
            field=models.CharField(max_length=13),
        ),
    ]
