# Generated by Django 4.2.6 on 2023-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0003_alter_captchaimage_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaimage',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1),
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='image_name',
            field=models.CharField(help_text='Max character length is 10', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='prompt_text',
            field=models.CharField(help_text='The prompt the user sees. Eg: "Select all the cars in the image" ', max_length=200),
        ),
    ]
