# Generated by Django 4.2.6 on 2023-11-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0004_captchaimage_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_json', models.TextField(null=True)),
                ('root_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='captchapractice.captchaimage')),
            ],
        ),
    ]
