# Generated by Django 4.2.6 on 2023-11-14 21:17

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0006_userresponses_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponses',
            name='user_name',
            field=models.TextField(blank=True, null=True, verbose_name=django.contrib.auth.base_user.AbstractBaseUser.get_username),
        ),
    ]
