# Generated by Django 4.2.6 on 2023-11-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0008_alter_userresponses_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponses',
            old_name='user_name',
            new_name='user',
        ),
    ]
