# Generated by Django 4.2.6 on 2023-11-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0010_alter_userresponses_response_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponses',
            name='response_json',
            field=models.TextField(null=True),
        ),
    ]
