# Generated by Django 4.2.6 on 2023-11-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0011_alter_userresponses_response_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_name', models.CharField(help_text='Max image name length is 10 characters', max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='image_name',
            field=models.CharField(help_text='Max image name length is 10 characters', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='response_json',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
