# Generated by Django 4.2.6 on 2023-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchapractice', '0012_uploadimage_alter_captchaimage_image_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AddField(
            model_name='captchaimage',
            name='image',
            field=models.ImageField(null=True, upload_to='admin uploads/'),
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='image_name',
            field=models.CharField(help_text='Enter an abbreviated image name (max length 10 characters). Do not include an extension', max_length=10, unique=True),
        ),
    ]
